import pandas as pd
import matplotlib.pyplot as plt

# Read results generated by run_mc.py
file = "PATH/TO/RESULTS.csv"
results = pd.read_csv(file)

# Group by frequency and calculate mean and standard deviation
param = 'spl_s'
grouped = results.groupby('frequency')[f'{param}'].agg(['mean', 'std']).reset_index()

# Create the plot
plt.figure(figsize=(12, 6))
plt.errorbar(grouped['frequency'], grouped['mean'], yerr=grouped['std'], 
             fmt='o-', capsize=5, capthick=1, ecolor='gray', markersize=4)

plt.xscale('log')
plt.xlabel('Frequency (Hz)')
plt.ylabel('SPL (dB)')
plt.title('SPL vs Frequency with Uncertainty')
plt.grid(True, which="both", ls="-", alpha=0.2)

plt.tight_layout()
plt.savefig('spl_vs_frequency.pdf', format='pdf', bbox_inches='tight')
plt.show()
